### ISSUE TITLE
Checklist for recent Lmod RPMs

### ISSUE THREAD

**Issue by fgeorgatos** [plabrop/bic#70]
* [x] `MODULEPATH*` variables get initialized as expected ; for both centos6 & centos7, with or w/out Tmod
* [x] `ml --gitversion` ; `module --version` report reasonable output, consistent to RPM package name
* [x] modules behave persistently and coherently across parent-children shell invocations (excl: `shared`?)
   * [x] invoking `bash` does NOT reset the environment, and lets `load`s and `use` operations be consistent
   * [x] invoking `tcsh` instead also preserves the modules environment as it should, without any surprises
   * [x] also, `module unload`s should function properly (fi. `-sge` vs empty `$LD_LIBRARY_PATH`) ref. issue #45 
* [x] `SitePackage.lua` gets honored and syslog messages get injected after `module load`
* [x] `module save`, `module savelist` and `module restore` behave correctly
* [x] `bash` tab completion should be OK too, also on successive operands; maybe also `zsh`
* [x] `$USER_IS_ROOT` has correct value, as well as `$LMOD_SYSTEM_DEFAULT_MODULES`
   * [x] functions work correctly for both `root` and non-`root` users
   * [x] `sge` and `cluster` modules, and any dependencies (fi. `$SITENAME`, get autoloaded)
* [x] `tcsh` and `bash` both initialize/behave correctly
   * [x] also under `qsub` and `qrsh`
   * [x] also under `crontab` (at least with `bash -l` support) & `at`
* [x] bash script tracing should work consistently at all times (#64)
* [x] and also pass: https://github.com/rtmclay/Lmod_test_suite (ok, modulo the infamous bash bug)

**Comment by jerowe** [comment]
pinging myself ;-)

**Comment by fgeorgatos** [comment]
@jerowe: if you are busy on a Bright environment, it is a perfect moment to recruit you as beta-tester ;-)
ref. http://support.brightcomputing.com/illumina-lmod/7.0/rhel/6/ (or ./7)

**Comment by fgeorgatos** [comment]
hi @jerowe : we are about to give out one more bugfixing RPM later today! 
r u interested to check it on a Bright cluster? (if you supply your users with Lmod over Bright, it worths it)

**Comment by fgeorgatos** [comment]
wow... all testing is passing so far with flying colors (modulo an infamous inherent bash issue to be handled in another thread); I'm closing this, we have a first production ready RPM here!

There are still some snags to fix on the current solution, but i won't call them blockers!
