### ISSUE TITLE
Items tasklist to go through for next Lmod RPM

### ISSUE THREAD

**Issue by fgeorgatos** [plabrop/bic#86]
This list looks long but they are all of them non-blockers, so the situation is quite good as of now.

* [x] `--version` & `--gitversion` (or git TAG pointing thereof) `SHOULD` match the package name; fi. #83 
* [x] `SitePackage.lua` could be a non-broken one :-) inspect that syslog entries work out of the box
  * fi. use https://github.com/TACC/Lmod/pull/273/files
  * also fix https://github.com/Bright-Computing/bic/issues/84
* [x] /usr/share/lmod/lmod/modulefiles/Core/settarg : This is a total MUST-have for developers
* [x] #81 : define in `.spec` file lua extensions as Bright Lmod RPM dependencies (what about repo?)
   * `yum localinstall lua-{bit32-0.2,filesystem-1.6.3,posix-33.4.0}-1000_cm7.0.x86_64.rpm`
   * ref. http://support.brightcomputing.com/illumina/
* [x] validate against FindFirst (D) bug, ie. https://github.com/TACC/Lmod/issues/275
    * [x] LMOD_TMOD_FIND_FIRST=true
    * Confirmed in: https://github.com/TACC/Lmod/issues/275#issuecomment-317841919
* [x] `module unuse` tab completion should work, too (it does work in manual Lmod delivery): 
   * Hint it only searches **existing** loaded modules
* [x] make `use.own.eb` be available per default, under `/etc/site/module` ?! (TBD)
* [x] Perhaps define automagically `EASYBUILD_MODULES_TOOL=Lmod` ?! (TBD, default modulefile?)
* [x] what if `$MODULEPATH` or `$LMOD_SYSTEM_DEFAULT_MODULES` need to be initialized externally to RPM files? how do this? (TBD)
* [x] related to last one, which would be the **right** place for handling `$LMOD*` environment variables? (TBD)
* [x] similarly, `$USER_IS_ROOT` probably should be external to the package (TBD)

and also:

* [ ] an empty `$LD_LIBRARY_PATH` should not trigger reinitialization of environment; ref. #55 
* [ ] `Lmod_test_suite` should provably be able to pass - automate any further testing via any of:
   * use [shell-doctest](https://github.com/michilu/shell-doctest) 
   * OR [cram](https://github.com/brodie/cram)
   * OR [bats](https://github.com/bats-core/bats-core)
   * OR [shtst](https://pypi.org/project/shtst/)
   ref. https://github.com/rtmclay/Lmod_test_suite 
* [ ] if possible, avoid the `BASH_ENV` modifications - bad karma, that may conflict with other packages
* [ ] pass once more through the hoops of the checklist at #70
